using System;
using System.ComponentModel.DataAnnotations;

namespace System.Web.Mvc
{
	[Author("André Gomes", "10/07/2019", Description = "Relação de Glyph Icons.")]
	public enum DynamicGlyphIconEnum
	{
		[EnumTitle("icon-glass")]
		glass,
		[EnumTitle("icon-music")]
		music,
		[EnumTitle("icon-search")]
		search,
		[EnumTitle("icon-envelope")]
		envelope,
		[EnumTitle("icon-heart")]
		heart,
		[EnumTitle("icon-star")]
		star,
		[EnumTitle("icon-star-empty")]
		star_empty,
		[EnumTitle("icon-user")]
		user,
		[EnumTitle("icon-film")]
		film,
		[EnumTitle("icon-th-large")]
		th_large,
		[EnumTitle("icon-th")]
		th,
		[EnumTitle("icon-th-list")]
		th_list,
		[EnumTitle("icon-ok")]
		ok,
		[EnumTitle("icon-remove")]
		remove,
		[EnumTitle("icon-zoom-in")]
		zoom_in,
		[EnumTitle("icon-zoom-out")]
		zoom_out,
		[EnumTitle("icon-off")]
		off,
		[EnumTitle("icon-signal")]
		signal,
		[EnumTitle("icon-cog")]
		cog,
		[EnumTitle("icon-trash")]
		trash,
		[EnumTitle("icon-home")]
		home,
		[EnumTitle("icon-file")]
		file,
		[EnumTitle("icon-time")]
		time,
		[EnumTitle("icon-road")]
		road,
		[EnumTitle("icon-download-alt")]
		download_alt,
		[EnumTitle("icon-download")]
		download,
		[EnumTitle("icon-upload")]
		upload,
		[EnumTitle("icon-inbox")]
		inbox,
		[EnumTitle("icon-play-circle")]
		play_circle,
		[EnumTitle("icon-repeat")]
		repeat,
		[EnumTitle("icon-refresh")]
		refresh,
		[EnumTitle("icon-list-alt")]
		list_alt,
		[EnumTitle("icon-lock")]
		@lock,
		[EnumTitle("icon-flag")]
		flag,
		[EnumTitle("icon-headphones")]
		headphones,
		[EnumTitle("icon-volume-off")]
		volume_off,
		[EnumTitle("icon-volume-down")]
		volume_down,
		[EnumTitle("icon-volume-up")]
		volume_up,
		[EnumTitle("icon-qrcode")]
		qrcode,
		[EnumTitle("icon-barcode")]
		barcode,
		[EnumTitle("icon-tag")]
		tag,
		[EnumTitle("icon-tags")]
		tags,
		[EnumTitle("icon-book")]
		book,
		[EnumTitle("icon-bookmark")]
		bookmark,
		[EnumTitle("icon-print")]
		print,
		[EnumTitle("icon-camera")]
		camera,
		[EnumTitle("icon-font")]
		font,
		[EnumTitle("icon-bold")]
		bold,
		[EnumTitle("icon-italic")]
		italic,
		[EnumTitle("icon-text-height")]
		text_height,
		[EnumTitle("icon-text-width")]
		text_width,
		[EnumTitle("icon-align-left")]
		align_left,
		[EnumTitle("icon-align-center")]
		align_center,
		[EnumTitle("icon-align-right")]
		align_right,
		[EnumTitle("icon-align-justify")]
		align_justify,
		[EnumTitle("icon-list")]
		list,
		[EnumTitle("icon-indent-left")]
		indent_left,
		[EnumTitle("icon-indent-right")]
		indent_right,
		[EnumTitle("icon-facetime-video")]
		facetime_video,
		[EnumTitle("icon-picture")]
		picture,
		[EnumTitle("icon-pencil")]
		pencil,
		[EnumTitle("icon-map-marker")]
		map_marker,
		[EnumTitle("icon-adjust")]
		adjust,
		[EnumTitle("icon-tint")]
		tint,
		[EnumTitle("icon-edit")]
		edit,
		[EnumTitle("icon-share")]
		share,
		[EnumTitle("icon-check")]
		check,
		[EnumTitle("icon-move")]
		move,
		[EnumTitle("icon-step-backward")]
		step_backward,
		[EnumTitle("icon-fast-backward")]
		fast_backward,
		[EnumTitle("icon-backward")]
		backward,
		[EnumTitle("icon-play")]
		play,
		[EnumTitle("icon-pause")]
		pause,
		[EnumTitle("icon-stop")]
		stop,
		[EnumTitle("icon-forward")]
		forward,
		[EnumTitle("icon-fast-forward")]
		fast_forward,
		[EnumTitle("icon-step-forward")]
		step_forward,
		[EnumTitle("icon-eject")]
		eject,
		[EnumTitle("icon-chevron-left")]
		chevron_left,
		[EnumTitle("icon-chevron-right")]
		chevron_right,
		[EnumTitle("icon-plus-sign")]
		plus_sign,
		[EnumTitle("icon-minus-sign")]
		minus_sign,
		[EnumTitle("icon-remove-sign")]
		remove_sign,
		[EnumTitle("icon-ok-sign")]
		ok_sign,
		[EnumTitle("icon-question-sign")]
		question_sign,
		[EnumTitle("icon-info-sign")]
		info_sign,
		[EnumTitle("icon-screenshot")]
		screenshot,
		[EnumTitle("icon-remove-circle")]
		remove_circle,
		[EnumTitle("icon-ok-circle")]
		ok_circle,
		[EnumTitle("icon-ban-circle")]
		ban_circle,
		[EnumTitle("icon-arrow-left")]
		arrow_left,
		[EnumTitle("icon-arrow-right")]
		arrow_right,
		[EnumTitle("icon-arrow-up")]
		arrow_up,
		[EnumTitle("icon-arrow-down")]
		arrow_down,
		[EnumTitle("icon-share-alt")]
		share_alt,
		[EnumTitle("icon-resize-full")]
		resize_full,
		[EnumTitle("icon-resize-small")]
		resize_small,
		[EnumTitle("icon-plus")]
		plus,
		[EnumTitle("icon-minus")]
		minus,
		[EnumTitle("icon-asterisk")]
		asterisk,
		[EnumTitle("icon-exclamation-sign")]
		exclamation_sign,
		[EnumTitle("icon-gift")]
		gift,
		[EnumTitle("icon-leaf")]
		leaf,
		[EnumTitle("icon-fire")]
		fire,
		[EnumTitle("icon-eye-open")]
		eye_open,
		[EnumTitle("icon-eye-close")]
		eye_close,
		[EnumTitle("icon-warning-sign")]
		warning_sign,
		[EnumTitle("icon-plane")]
		plane,
		[EnumTitle("icon-calendar")]
		calendar,
		[EnumTitle("icon-random")]
		random,
		[EnumTitle("icon-comment")]
		comment,
		[EnumTitle("icon-magnet")]
		magnet,
		[EnumTitle("icon-chevron-up")]
		chevron_up,
		[EnumTitle("icon-chevron-down")]
		chevron_down,
		[EnumTitle("icon-retweet")]
		retweet,
		[EnumTitle("icon-shopping-cart")]
		shopping_cart,
		[EnumTitle("icon-folder-close")]
		folder_close,
		[EnumTitle("icon-folder-open")]
		folder_open,
		[EnumTitle("icon-resize-vertical")]
		resize_vertical,
		[EnumTitle("icon-resize-horizontal")]
		resize_horizontal,
		[EnumTitle("icon-hdd")]
		hdd,
		[EnumTitle("icon-bullhorn")]
		bullhorn,
		[EnumTitle("icon-bell")]
		bell,
		[EnumTitle("icon-certificate")]
		certificate,
		[EnumTitle("icon-thumbs-up")]
		thumbs_up,
		[EnumTitle("icon-thumbs-down")]
		thumbs_down,
		[EnumTitle("icon-hand-right")]
		hand_right,
		[EnumTitle("icon-hand-left")]
		hand_left,
		[EnumTitle("icon-hand-up")]
		hand_up,
		[EnumTitle("icon-hand-down")]
		hand_down,
		[EnumTitle("icon-circle-arrow-right")]
		circle_arrow_right,
		[EnumTitle("icon-circle-arrow-left")]
		circle_arrow_left,
		[EnumTitle("icon-circle-arrow-up")]
		circle_arrow_up,
		[EnumTitle("icon-circle-arrow-down")]
		circle_arrow_down,
		[EnumTitle("icon-globe")]
		globe,
		[EnumTitle("icon-wrench")]
		wrench,
		[EnumTitle("icon-tasks")]
		tasks,
		[EnumTitle("icon-filter")]
		filter,
		[EnumTitle("icon-briefcase")]
		briefcase,
		[EnumTitle("icon-fullscreen")]
		fullscreen
	}
}